/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mockLidoSol from "./MockLido.sol";
export type { mockLidoSol };
import type * as mockUniswapSol from "./MockUniswap.sol";
export type { mockUniswapSol };
export type { MockAggregatorV3 } from "./MockAggregatorV3";
export type { MockERC20 } from "./MockERC20";
export type { MockVault } from "./MockVault";
