/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as oracleAdapterSol from "./OracleAdapter.sol";
export type { oracleAdapterSol };
export type { CollateralManager } from "./CollateralManager";
export type { MasterVault } from "./MasterVault";
export type { RiskManager } from "./RiskManager";
export type { Stablecoin } from "./Stablecoin";
