/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as lidoAdapterSol from "./LidoAdapter.sol";
export type { lidoAdapterSol };
export type { LidoAdapterTestnet } from "./LidoAdapterTestnet";
