/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IVault } from "./IVault";
export type { LSTVault } from "./LSTVault";
export type { RWAVault } from "./RWAVault";
